version: "3"

services:

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./mysql/srv/conf.d:/etc/mysql/conf.d
      - ./mysql/srv/initdb.d:/docker-entrypoint-initdb.d
      - ${MYSQL_VOLUME:-mysql-volume}:/var/lib/mysql:Z
    networks:
      - backend
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}

  freeradius:
    image: zentekmx/freeradius
    ports:
      - 1812:1812/udp
      - 1813:1813/udp
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      - DB_HOST=mysql
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_PORT=${MYSQL_PORT}
      - RADIUS_KEY

  php:
    build:
      context: ./
    ports:
      - 80:80
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - backend
    environment:
      - DB_HOST=mysql
      - DB_PORT=${MYSQL_PORT}
      - DB_DATABASE=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}

volumes:
  mysql-volume:

networks:
  backend:
    ipam:
      config:
        - subnet: 172.16.0.0/16

